PUT http://localhost:3000/users/12
Content-Type: application/json

{
  "name": "scott",
  "username": "zilla",
  "email": "godzilla@gmail.com",
  "address": {
    "street": "Sleep Street",
    "suite": "Suite 420",
    "city": "Queens",
    "zipcode": "11377",
    "geo": {
      "lat": "-31.8129",
      "lng": "62.5342"
    }
  },
  "phone": "(254)954-1289",
  "website": "demarco.info",
  "company": {
    "name": "Keebler LLC",
    "catchPhrase": "User-centric fault-tolerant solution",
    "bs": "revolutionize end-to-end systems"
  }
}